<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Nette\Utils\Random;
use Ramsey\Uuid\Type\Integer;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('members')->insert([
            [
                'user_id' => '1',
                'business_name' => 'Kamal f&b',
                'business_category' => 'kuliner basah',
                'business_duration' => '4',
                'owner_name' => 'Ahmad Kamaludin',
                'phone_number' => '6281901035799',
                'province' => 'JAWA TENGAH',
                'city' => 'Tegal',
                'sub_district' => 'Suradadi',
                'village' => 'Purwahamba',
                'address' => 'jl pemuda, Desa Purwahamba, kec. Suradadi, KAB.Tegal, Jawa Tengah',
                'id_card_number' => '3302930930239' ,
                'id_card_photo' => 'photo.jpg',
                'id_card_selfie' => 'selfie.jpg',
                // 'product_photo' => 'product.jpg',
                'bank_name' => 'BANK MANDIRI',
                'bank_account_number' => '20339329298',
                'bank_holders_name' => 'Ahmad Kamaludin',
                'nib_license' => 'nib93920280',
                'halal_license' => 'halal232892090',
                'pirt_license' => 'pirt237239030',
                'bpom_license' => 'bpom2932300282',
                'hki_license' => 'hki1929239',
                'nutrition_test_license' => 'nutrition99238920',
                'haccp_license' => 'haccp020120939',
                // 'request_activation' => true,
                // 'request_verification' => true,
                // 'verification' => '02382308239',
                // 'qr_code_path' => 'ksioweojsk',
            ],
            [
                'user_id' => '2',
                'business_name' => 'Nice Cookies',
                'business_category' => 'kuliner kering',
                'business_duration' => '4',
                'owner_name' => 'Raihan Galih',
                'phone_number' => ('62'. rand(0, 120000000000)),
                'province' => 'JAWA TENGAH',
                'city' => 'Tegal',
                'sub_district' => 'Suradadi',
                'village' => 'Purwahamba',
                'id_card_number' => rand(0, 120000000000),
                'address' => 'jl pemuda, Desa Purwahamba, kec. Suradadi, KAB.Tegal, Jawa Tengah',
                'id_card_photo' => 'photo.jpg',
                'id_card_selfie' => 'selfie.jpg',
                // 'product_photo' => 'product.jpg',
                'bank_name' => 'BANK MANDIRI',
                'bank_account_number' => rand(0, 1200000000),
                'bank_holders_name' => 'Raihan Galih',
                'nib_license' => ('nib'. rand(0, 120000000)),
                'halal_license' => ('halal'. rand(0, 120000000)),
                'pirt_license' => ('pirt'. rand(0, 120000000)),
                'bpom_license' => ('bpom'. rand(0, 120000000)),
                'hki_license' => ('hki'. rand(0, 120000000)),
                'nutrition_test_license' => ('nutrition'. rand(0, 120000000)),
                'haccp_license' => ('haccp'. rand(0, 120000000)),
                // 'request_activation' => true,
                // 'request_verification' => true,
                // 'verification' => '02382308239',
                // 'qr_code_path' => 'ksioweojsk',
                
            ],
            [
                'user_id' => '3',
                'business_name' => "Yulita's Fashion",
                'business_category' => 'fashion',
                'business_duration' => '4',
                'owner_name' => 'Yulita Dwi Syahrotin',
                'phone_number' => '6288226713099',
                'province' => 'JAWA TENGAH',
                'city' => 'Tegal',
                'sub_district' => 'Suradadi',
                'village' => 'Kertasari',
                'id_card_number' => '3302930930239',
                'address' => 'jl pemuda, Desa Purwahamba, kec. Suradadi, KAB.Tegal, Jawa Tengah',
                'id_card_photo' => 'photo.jpg',
                'id_card_selfie' => 'selfie.jpg',
                // 'product_photo' => 'product.jpg',
                'bank_name' => 'BANK MANDIRI',
                'bank_account_number' => '20339329298',
                'bank_holders_name' => 'Yulita Dwi Syahrotin',
                'nib_license' => 'nib93920280',
                'halal_license' => 'halal232892090',
                'pirt_license' => 'pirt237239030',
                'bpom_license' => 'bpom2932300282',
                'hki_license' => 'hki1929239',
                'nutrition_test_license' => 'nutrition99238920',
                'haccp_license' => 'haccp020120939',
                // 'request_activation' => true,
                // 'request_verification' => true,
                // 'verification' => '02382308239',
                // 'qr_code_path' => 'ksioweojsk',
            ],
            [
                'user_id' => '4',
                'business_name' => "Anterin kuy",
                'business_category' => 'jasa',
                'business_duration' => '6',
                'owner_name' => 'Rafki',
                'phone_number' => '6285741148380',
                'province' => 'JAWA TENGAH',
                'city' => 'Tegal',
                'sub_district' => 'Kramat',
                'village' => 'Bongkok',
                'id_card_number' => '3302930930239',
                'address' => 'jl pemuda, Desa Purwahamba, kec. Suradadi, KAB.Tegal, Jawa Tengah',
                'id_card_photo' => 'photo.jpg',
                'id_card_selfie' => 'selfie.jpg',
                // 'product_photo' => 'product.jpg',
                'bank_name' => 'BANK MANDIRI',
                'bank_account_number' => '20339329298',
                'bank_holders_name' => 'Rafki',
                'nib_license' => 'nib93920280',
                'halal_license' => 'halal232892090',
                'pirt_license' => 'pirt237239030',
                'bpom_license' => 'bpom2932300282',
                'hki_license' => 'hki1929239',
                'nutrition_test_license' => 'nutrition99238920',
                'haccp_license' => 'haccp020120939',
                // 'request_activation' => false,
                // 'request_verification' => false,
                // // 'verification' => '02382308239',
                // // 'qr_code_path' => 'ksioweojsk',
            ],
            [
                'user_id' => '5',
                'business_name' => "Fadhil's craft",
                'business_category' => 'craft',
                'business_duration' => '3',
                'owner_name' => 'Fadhil Triatmaja',
                'phone_number' => '628551231400',
                'province' => 'JAWA TENGAH',
                'city' => 'Tegal',
                'sub_district' => 'Kramat',
                'village' => 'Babakan',
                'id_card_number' => '3302930930239',
                'address' => 'jl pemuda, Desa Purwahamba, kec. Suradadi, KAB.Tegal, Jawa Tengah',
                'id_card_photo' => 'photo.jpg',
                'id_card_selfie' => 'selfie.jpg',
                // 'product_photo' => 'product.jpg',
                'bank_name' => 'BANK MANDIRI',
                'bank_account_number' => '20339329298',
                'bank_holders_name' => 'Fadhil Triatmaja',
                'nib_license' => 'nib93920280',
                'halal_license' => 'halal232892090',
                'pirt_license' => 'pirt237239030',
                'bpom_license' => 'bpom2932300282',
                'hki_license' => 'hki1929239',
                'nutrition_test_license' => 'nutrition99238920',
                'haccp_license' => 'haccp020120939',
                // 'request_activation' => false,
                // 'request_verification' => false,
                // 'verification' => '02382308239',
                // 'qr_code_path' => 'ksioweojsk',
            ],
            [
                'user_id' => '6',
                'business_name' => 'Fresh Drink',
                'business_category' => 'drink',
                'business_duration' => '4',
                'owner_name' => 'Rahmatullah',
                'phone_number' => ('62'. rand(0, 120000000000)),
                'province' => 'JAWA TENGAH',
                'city' => 'Tegal',
                'sub_district' => 'Suradadi',
                'village' => 'Purwahamba',
                'id_card_number' => rand(0, 120000000000),
                'address' => 'jl pemuda, Desa Purwahamba, kec. Suradadi, KAB.Tegal, Jawa Tengah',
                'id_card_photo' => 'photo.jpg',
                'id_card_selfie' => 'selfie.jpg',
                // 'product_photo' => 'product.jpg',
                'bank_name' => 'BANK MANDIRI',
                'bank_account_number' => rand(0, 1200000000),
                'bank_holders_name' => 'Rahmatullah',
                'nib_license' => ('nib'. rand(0, 120000000)),
                'halal_license' => ('halal'. rand(0, 120000000)),
                'pirt_license' => ('pirt'. rand(0, 120000000)),
                'bpom_license' => ('bpom'. rand(0, 120000000)),
                'hki_license' => ('hki'. rand(0, 120000000)),
                'nutrition_test_license' => ('nutrition'. rand(0, 120000000)),
                'haccp_license' => ('haccp'. rand(0, 120000000)),
                // 'request_activation' => true,
                // 'request_verification' => true,
                // 'verification' => '02382308239',
                // 'qr_code_path' => 'ksioweojsk',  
            ],
            [
                'user_id' => '7',
                'business_name' => 'True Beauty',
                'business_category' => 'beauty',
                'business_duration' => '4',
                'owner_name' => 'Yulita Dwi Syahrotin',
                'phone_number' => ('62'. rand(0, 120000000000)),
                'province' => 'JAWA TENGAH',
                'city' => 'Tegal',
                'sub_district' => 'Suradadi',
                'village' => 'Purwahamba',
                'id_card_number' => rand(0, 120000000000),
                'address' => 'jl pemuda, Desa Purwahamba, kec. Suradadi, KAB.Tegal, Jawa Tengah',
                'id_card_photo' => 'photo.jpg',
                'id_card_selfie' => 'selfie.jpg',
                // 'product_photo' => 'product.jpg',
                'bank_name' => 'BANK MANDIRI',
                'bank_account_number' => rand(0, 1200000000),
                'bank_holders_name' => 'Yulita Dwi Syahrotin',
                'nib_license' => ('nib'. rand(0, 120000000)),
                'halal_license' => ('halal'. rand(0, 120000000)),
                'pirt_license' => ('pirt'. rand(0, 120000000)),
                'bpom_license' => ('bpom'. rand(0, 120000000)),
                'hki_license' => ('hki'. rand(0, 120000000)),
                'nutrition_test_license' => ('nutrition'. rand(0, 120000000)),
                'haccp_license' => ('haccp'. rand(0, 120000000)),
                // 'request_activation' => true,
                // 'request_verification' => true,
                // 'verification' => '02382308239',
                // 'qr_code_path' => 'ksioweojsk',
                
            ],
            [
                'user_id' => '8',
                'business_name' => 'Joko Furniture',
                'business_category' => 'furniture',
                'business_duration' => '4',
                'owner_name' => 'Joko',
                'phone_number' => ('62'. rand(0, 120000000000)),
                'province' => 'JAWA TENGAH',
                'city' => 'Tegal',
                'sub_district' => 'Suradadi',
                'village' => 'Purwahamba',
                'id_card_number' => rand(0, 120000000000),
                'address' => 'jl pemuda, Desa Purwahamba, kec. Suradadi, KAB.Tegal, Jawa Tengah',
                'id_card_photo' => 'photo.jpg',
                'id_card_selfie' => 'selfie.jpg',
                // 'product_photo' => 'product.jpg',
                'bank_name' => 'BANK MANDIRI',
                'bank_account_number' => rand(0, 1200000000),
                'bank_holders_name' => 'Joko',
                'nib_license' => ('nib'. rand(0, 120000000)),
                'halal_license' => ('halal'. rand(0, 120000000)),
                'pirt_license' => ('pirt'. rand(0, 120000000)),
                'bpom_license' => ('bpom'. rand(0, 120000000)),
                'hki_license' => ('hki'. rand(0, 120000000)),
                'nutrition_test_license' => ('nutrition'. rand(0, 120000000)),
                'haccp_license' => ('haccp'. rand(0, 120000000)),
                // 'request_activation' => true,
                // 'request_verification' => true,
                // 'verification' => '02382308239',
                // 'qr_code_path' => 'ksioweojsk',
                
            ],
        ]);
    }
}
